title: <p align="center"> Praveen Kumar </p>
logo: /assets/img/pic.jpg
description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://https://www.linkedin.com/in/its-praveenkumar/">LinkedIn</a> |
  <a href="https://github.com/praveenkumar5188">GitHub</a>
  
  <br>   
  I'm working on C++ in Audio domain for Automotive.
  Working in Harman International since 2 years.
  <br>
  </p>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
